# Generated by Django 6.0.6 on 2026-07-07 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=64)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='catalog.product')),
            ],
            options={
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['expiry_date'], name='lots_lot_expiry__2c286b_idx'), models.Index(fields=['product', 'expiry_date'], name='lots_lot_product_1d773e_idx'), models.Index(fields=['batch_number'], name='lots_lot_batch_n_83b0f3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='lot_qty_nonneg')],
            },
        ),
    ]
