"""REST API ViewSets for the intelligence (AI/ML) module.

Provides CRUD / read-only endpoints for all AI artifacts plus dashboard
aggregations and LLM-triggered insights.
"""

from __future__ import annotations

from datetime import date, timedelta

from django.db.models import Count, OuterRef, Q, Subquery
from django.utils import timezone
from rest_framework import status, viewsets
from rest_framework.decorators import action, api_view, permission_classes
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.response import Response

from django.contrib.auth import get_user_model
from apps.accounts.permissions import RoleAllowed
UserModel = get_user_model()
from apps.intelligence.models import (
    AIModuleConfig,
    AnomalyAlert,
    DemandForecast,
    DocumentTemplate,
    ExpiryRiskAssessment,
    ModelVersion,
    PatientAdherenceScore,
    PredictionLog,
    SupplierScore,
)
from apps.intelligence.serializers import (
    AIModuleConfigSerializer,
    AIConfigSerializer,
    AnomalyAlertResolveSerializer,
    AnomalyAlertSerializer,
    DemandForecastSerializer,
    DocumentTemplateSerializer,
    ExpiryRiskAssessmentSerializer,
    InsightRequestSerializer,
    ModelVersionSerializer,
    PatientAdherenceScoreSerializer,
    SupplierScoreSerializer,
)

# ---------------------------------------------------------------------------
# Permission shortcuts
# ---------------------------------------------------------------------------
_ADMIN_WRITE = RoleAllowed({"ADMIN": "write"})
_ADMIN_PHARM_WRITE = RoleAllowed({"ADMIN": "write", "PHARMACIST": "write"})


# ===================================================================
# ModelVersion
# ===================================================================


class ModelVersionViewSet(viewsets.ReadOnlyModelViewSet):
    """List and retrieve AI model versions.

    By default returns only active versions.  Pass ``?all=1`` to see
    every version ever registered.
    """

    serializer_class = ModelVersionSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        qs = ModelVersion.objects.annotate(
            prediction_count=Count("predictions")
        ).order_by("model_type", "-created_at")

        if not self.request.query_params.get("all"):
            qs = qs.filter(is_active=True)
        return qs


# ===================================================================
# DemandForecast
# ===================================================================


class DemandForecastViewSet(viewsets.ReadOnlyModelViewSet):
    """Per-product demand forecasts generated by the prediction engine.

    Filters
    -------
    * ``product`` -- UUID of a catalog.Product
    * ``from_date`` / ``to_date`` -- ISO date range on ``forecast_date``
    * ``method`` -- forecasting method name
    """

    serializer_class = DemandForecastSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        qs = (
            DemandForecast.objects.select_related("product", "model_version")
            .order_by("-forecast_date", "-predicted_quantity")
        )

        product = self.request.query_params.get("product")
        if product:
            qs = qs.filter(product_id=product)

        from_date = self.request.query_params.get("from_date")
        if from_date:
            qs = qs.filter(forecast_date__gte=from_date)

        to_date = self.request.query_params.get("to_date")
        if to_date:
            qs = qs.filter(forecast_date__lte=to_date)

        method = self.request.query_params.get("method")
        if method:
            qs = qs.filter(method=method)

        return qs


# ===================================================================
# SupplierScore
# ===================================================================


class SupplierScoreViewSet(viewsets.ReadOnlyModelViewSet):
    """Per-supplier composite scores (cost, reliability, quality, speed).

    Filters
    -------
    * ``supplier`` -- UUID of a catalog.Supplier
    * ``trend`` -- ``rising`` / ``falling`` / ``stable``
    """

    serializer_class = SupplierScoreSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        qs = (
            SupplierScore.objects.select_related("supplier")
            .order_by("-overall_score")
        )

        supplier = self.request.query_params.get("supplier")
        if supplier:
            qs = qs.filter(supplier_id=supplier)

        trend = self.request.query_params.get("trend")
        if trend:
            qs = qs.filter(trend=trend)

        return qs


# ===================================================================
# ExpiryRiskAssessment
# ===================================================================


class ExpiryRiskAssessmentViewSet(viewsets.ReadOnlyModelViewSet):
    """Per-lot expiry risk assessments.

    Filters
    -------
    * ``lot`` -- UUID of a lots.Lot
    * ``risk_level`` -- ``critical`` / ``high`` / ``medium`` / ``low``
    """

    serializer_class = ExpiryRiskAssessmentSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        qs = ExpiryRiskAssessment.objects.select_related(
            "lot__product"
        ).order_by("-risk_score")

        lot = self.request.query_params.get("lot")
        if lot:
            qs = qs.filter(lot_id=lot)

        risk_level = self.request.query_params.get("risk_level")
        if risk_level:
            qs = qs.filter(risk_level=risk_level)

        return qs


# ===================================================================
# AnomalyAlert
# ===================================================================


class AnomalyAlertViewSet(viewsets.ModelViewSet):
    """Detected statistical anomalies.

    Read-write for resolution.  By default returns only unresolved alerts.
    Pass ``?all=1`` to include resolved items.

    Filters
    -------
    * ``anomaly_type`` -- e.g. ``unusual_order``, ``stock_discrepancy``
    * ``severity`` -- ``low`` / ``medium`` / ``high`` / ``critical``
    * ``subject_type`` -- e.g. ``product``, ``supplier``, ``order``
    * ``resolved`` -- ``true`` or ``false``
    """

    serializer_class = AnomalyAlertSerializer
    permission_classes = [IsAuthenticated, _ADMIN_PHARM_WRITE]

    def get_queryset(self):
        qs = AnomalyAlert.objects.select_related(
            "resolved_by"
        ).order_by("-created_at")

        if not self.request.query_params.get("all"):
            qs = qs.filter(resolved=False)

        anomaly_type = self.request.query_params.get("anomaly_type")
        if anomaly_type:
            qs = qs.filter(anomaly_type=anomaly_type)

        severity = self.request.query_params.get("severity")
        if severity:
            qs = qs.filter(severity=severity)

        subject_type = self.request.query_params.get("subject_type")
        if subject_type:
            qs = qs.filter(subject_type=subject_type)

        resolved_param = self.request.query_params.get("resolved")
        if resolved_param is not None:
            qs = qs.filter(resolved=resolved_param.lower() == "true")

        return qs

    @action(detail=True, methods=["post"])
    def resolve(self, request, pk=None):
        """Mark an anomaly alert as resolved."""
        alert = self.get_object()
        serializer = AnomalyAlertResolveSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        alert.resolved = True
        alert.resolved_by = request.user

        if serializer.validated_data.get("resolution_note"):
            existing = alert.data_snapshot or {}
            existing["resolution_note"] = serializer.validated_data["resolution_note"]
            alert.data_snapshot = existing

        alert.save(update_fields=["resolved", "resolved_by", "data_snapshot"])

        return Response(
            AnomalyAlertSerializer(alert).data, status=status.HTTP_200_OK
        )

    @action(detail=True, methods=["post"])
    def explain(self, request, pk=None):
        """Use the LLM to generate a plain-English explanation of this anomaly."""
        alert = self.get_object()
        try:
            from apps.intelligence.services.llm_insights import explain_anomaly

            explanation = explain_anomaly(str(alert.id))
            return Response(
                {"anomaly_id": str(alert.id), "explanation": explanation},
                status=status.HTTP_200_OK,
            )
        except ImportError:
            return Response(
                {"detail": "LLM insights module is not available."},
                status=status.HTTP_501_NOT_IMPLEMENTED,
            )
        except Exception as exc:
            return Response(
                {"detail": f"LLM call failed: {exc}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )


# ===================================================================
# PatientAdherenceScore
# ===================================================================


class PatientAdherenceScoreViewSet(viewsets.ReadOnlyModelViewSet):
    """Per-patient medication adherence scores.

    Filters
    -------
    * ``contact`` -- UUID of a crm.Contact
    * ``product`` -- UUID of a catalog.Product
    * ``pattern`` -- ``regular`` / ``declining`` / ``irregular`` / ``new``
    """

    serializer_class = PatientAdherenceScoreSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        qs = PatientAdherenceScore.objects.select_related(
            "contact", "product"
        ).order_by("adherence_score")

        contact = self.request.query_params.get("contact")
        if contact:
            qs = qs.filter(contact_id=contact)

        product = self.request.query_params.get("product")
        if product:
            qs = qs.filter(product_id=product)

        pattern = self.request.query_params.get("pattern")
        if pattern:
            qs = qs.filter(pattern=pattern)

        return qs


# ===================================================================
# DocumentTemplate
# ===================================================================


class DocumentTemplateViewSet(viewsets.ModelViewSet):
    """CRUD for LLM document-ingestion prompt templates (admin only)."""

    queryset = DocumentTemplate.objects.all().order_by("template_type")
    serializer_class = DocumentTemplateSerializer
    permission_classes = [IsAuthenticated, _ADMIN_WRITE]


# ===================================================================
# Dashboard aggregations + pipeline trigger
# ===================================================================


class IntelligenceDashboardViewSet(viewsets.ViewSet):
    """Aggregated endpoints that power the AI Intelligence dashboard.

    Not backed by a single model -- each ``@action`` queries across
    multiple intelligence tables.
    """

    permission_classes = [IsAuthenticated]

    # ------------------------------------------------------------------
    # Performance summary
    # ------------------------------------------------------------------

    @action(detail=False, methods=["get"])
    def performance(self, request):
        """Aggregated model performance for the AI dashboard.

        Returns per-model-type accuracy, total predictions (last 30 days),
        and the count of active model versions.
        """
        active_models = ModelVersion.objects.filter(is_active=True).annotate(
            pred_count=Count("predictions"),
            recent_preds=Count(
                "predictions",
                filter=Q(
                    predictions__created_at__gte=timezone.now()
                    - timedelta(days=30)
                ),
            ),
        )

        perf_rows = []
        for mv in active_models:
            accuracy = mv.accuracy_score

            # Fall back to live evaluation if available
            if accuracy is None:
                try:
                    from apps.intelligence.services.feedback_loop import evaluate_model

                    eval_result = evaluate_model(mv.model_type)
                    accuracy = eval_result.get("accuracy")
                except Exception:
                    accuracy = None

            perf_rows.append(
                {
                    "model_type": mv.model_type,
                    "model_type_display": mv.get_model_type_display(),
                    "version": mv.version,
                    "is_active": mv.is_active,
                    "accuracy": accuracy,
                    "total_predictions": mv.pred_count,
                    "recent_predictions_30d": mv.recent_preds,
                    "needs_retraining": accuracy is not None and accuracy < 0.7,
                    "last_trained": mv.last_trained_at or mv.created_at,
                }
            )

        # Top-level KPIs
        thirty_days_ago = timezone.now() - timedelta(days=30)
        total_preds_30d = PredictionLog.objects.filter(
            created_at__gte=thirty_days_ago
        ).count()
        unresolved_anomalies = AnomalyAlert.objects.filter(resolved=False).count()
        avg_accuracy = None
        accuracies = [r["accuracy"] for r in perf_rows if r["accuracy"] is not None]
        if accuracies:
            avg_accuracy = round(sum(accuracies) / len(accuracies), 4)

        return Response(
            {
                "kpis": {
                    "active_models": active_models.count(),
                    "total_predictions_30d": total_preds_30d,
                    "avg_accuracy": avg_accuracy,
                    "unresolved_anomalies": unresolved_anomalies,
                },
                "models": perf_rows,
            }
        )

    # ------------------------------------------------------------------
    # Dashboard summary stats
    # ------------------------------------------------------------------

    @action(detail=False, methods=["get"])
    def summary(self, request):
        """Quick counts for the dashboard cards."""
        thirty_days_ago = timezone.now() - timedelta(days=30)

        return Response(
            {
                "active_models": ModelVersion.objects.filter(is_active=True).count(),
                "total_predictions_30d": PredictionLog.objects.filter(
                    created_at__gte=thirty_days_ago
                ).count(),
                "unresolved_anomalies": AnomalyAlert.objects.filter(
                    resolved=False
                ).count(),
                "total_forecasts": DemandForecast.objects.count(),
                "critical_expiry_risks": ExpiryRiskAssessment.objects.filter(
                    risk_level="critical"
                ).count(),
                "high_expiry_risks": ExpiryRiskAssessment.objects.filter(
                    risk_level="high"
                ).count(),
                "low_adherence_patients": PatientAdherenceScore.objects.filter(
                    adherence_score__lt=50
                ).count(),
            }
        )

    # ------------------------------------------------------------------
    # Top demand forecasts (for dashboard table)
    # ------------------------------------------------------------------

    @action(detail=False, methods=["get"])
    def top_forecasts(self, request):
        """Return the latest forecast for each product, limited to top N."""
        limit = int(request.query_params.get("limit", 10))

        # Get latest forecast per product via subquery
        latest_per_product = (
            DemandForecast.objects.filter(product=OuterRef("product"))
            .order_by("-forecast_date")
        )

        forecasts = (
            DemandForecast.objects.filter(
                id=Subquery(latest_per_product.values("id")[:1])
            )
            .select_related("product", "model_version")
            .order_by("-predicted_quantity")[:limit]
        )

        serializer = DemandForecastSerializer(forecasts, many=True)
        return Response(serializer.data)

    # ------------------------------------------------------------------
    # Latest supplier scores (for dashboard table)
    # ------------------------------------------------------------------

    @action(detail=False, methods=["get"])
    def top_suppliers(self, request):
        """Return the latest score for each supplier, ordered by overall_score."""
        limit = int(request.query_params.get("limit", 10))

        latest_per_supplier = (
            SupplierScore.objects.filter(supplier=OuterRef("supplier"))
            .order_by("-calculated_at")
        )

        scores = (
            SupplierScore.objects.filter(
                id=Subquery(latest_per_supplier.values("id")[:1])
            )
            .select_related("supplier")
            .order_by("-overall_score")[:limit]
        )

        serializer = SupplierScoreSerializer(scores, many=True)
        return Response(serializer.data)

    # ------------------------------------------------------------------
    # Recent anomalies (for dashboard feed)
    # ------------------------------------------------------------------

    @action(detail=False, methods=["get"])
    def recent_anomalies(self, request):
        """Recent unresolved anomalies for the dashboard timeline."""
        limit = int(request.query_params.get("limit", 20))

        alerts = (
            AnomalyAlert.objects.filter(resolved=False)
            .select_related("resolved_by")
            .order_by("-created_at")[:limit]
        )

        serializer = AnomalyAlertSerializer(alerts, many=True)
        return Response(serializer.data)

    # ------------------------------------------------------------------
    # Expiry risk cards (for dashboard)
    # ------------------------------------------------------------------

    @action(detail=False, methods=["get"])
    def expiry_risks(self, request):
        """High/critical expiry risks for dashboard cards."""
        limit = int(request.query_params.get("limit", 12))

        risks = (
            ExpiryRiskAssessment.objects.filter(
                risk_level__in=["critical", "high"]
            )
            .select_related("lot__product")
            .order_by("-risk_score")[:limit]
        )

        serializer = ExpiryRiskAssessmentSerializer(risks, many=True)
        return Response(serializer.data)

    # ------------------------------------------------------------------
    # Trigger full pipeline
    # ------------------------------------------------------------------

    @action(detail=False, methods=["post"])
    def run_pipeline(self, request):
        """Execute the full intelligence pipeline and return results summary."""
        try:
            from apps.intelligence.services.run_pipeline import (
                run_full_intelligence_pipeline,
            )

            results = run_full_intelligence_pipeline()
            return Response(results, status=status.HTTP_200_OK)
        except ImportError:
            return Response(
                {"detail": "Pipeline module is not available."},
                status=status.HTTP_501_NOT_IMPLEMENTED,
            )
        except Exception as exc:
            return Response(
                {"detail": f"Pipeline execution failed: {exc}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

    # ------------------------------------------------------------------
    # LLM Insights
    # ------------------------------------------------------------------

    @action(detail=False, methods=["post"])
    def insights(self, request):
        """Trigger LLM-powered procurement recommendation or dashboard summary."""
        req_serializer = InsightRequestSerializer(data=request.data)
        req_serializer.is_valid(raise_exception=True)

        insight_type = req_serializer.validated_data["insight_type"]
        anomaly_id = req_serializer.validated_data.get("anomaly_id")
        supplier_ids = req_serializer.validated_data.get("supplier_ids", [])

        try:
            from apps.intelligence.services.llm_insights import (
                generate_procurement_recommendation,
                generate_dashboard_summary,
                explain_anomaly,
            )

            if insight_type == "procurement_recommendation":
                result = generate_procurement_recommendation()
            elif insight_type == "dashboard_summary":
                result = generate_dashboard_summary()
            elif insight_type == "anomaly_explanation":
                if not anomaly_id:
                    return Response(
                        {"detail": "anomaly_id is required for anomaly_explanation."},
                        status=status.HTTP_400_BAD_REQUEST,
                    )
                result = explain_anomaly(str(anomaly_id))
            else:
                return Response(
                    {"detail": f"Unknown insight_type: {insight_type}"},
                    status=status.HTTP_400_BAD_REQUEST,
                )

            return Response(
                {"insight_type": insight_type, "result": result},
                status=status.HTTP_200_OK,
            )
        except ImportError:
            return Response(
                {"detail": "LLM insights module is not available."},
                status=status.HTTP_501_NOT_IMPLEMENTED,
            )
        except Exception as exc:
            return Response(
                {"detail": f"LLM insight generation failed: {exc}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )


# ---------------------------------------------------------------------------
# AI Settings configuration (for the frontend SettingsAI page)
# ---------------------------------------------------------------------------
@api_view(["GET", "PATCH"])
@permission_classes([IsAuthenticated])
def ai_settings(request):
    """
    GET  /api/settings/ai/    → returns all module configs + retraining schedule
    PATCH /api/settings/ai/   → update module configs and/or retraining schedule
    """
    import django.conf as _django_conf

    if request.method == "GET":
        modules = AIModuleConfig.objects.all()
        serializer = AIConfigSerializer({
            "modules": modules,
            "retraining_schedule": getattr(_django_conf.settings, "AI_RETRAINING_SCHEDULE", "weekly"),
        })
        return Response(serializer.data)

    # PATCH
    serializer = AIConfigSerializer(data=request.data)
    serializer.is_valid(raise_exception=True)

    modules_data = serializer.validated_data.get("modules", [])
    for mod in modules_data:
        AIModuleConfig.objects.update_or_create(
            key=mod["key"],
            defaults={
                "label": mod.get("label", ""),
                "description": mod.get("description", ""),
                "enabled": mod.get("enabled", True),
                "confidence_threshold": mod.get("confidence_threshold", 0.7),
            },
        )

    if "retraining_schedule" in serializer.validated_data:
        _django_conf.settings.AI_RETRAINING_SCHEDULE = serializer.validated_data["retraining_schedule"]

    modules = AIModuleConfig.objects.all()
    result = AIConfigSerializer({
        "modules": modules,
        "retraining_schedule": getattr(_django_conf.settings, "AI_RETRAINING_SCHEDULE", "weekly"),
    })
    return Response(result.data)


# ---------------------------------------------------------------------------
# Theme Settings (for the frontend SettingsTheme page)
# ---------------------------------------------------------------------------
@api_view(["GET", "PATCH"])
@permission_classes([IsAuthenticated])
def theme_settings(request):
    """
    GET  /api/settings/theme/    → return theme preferences for the current user
    PATCH /api/settings/theme/   → update theme preferences for the current user
    """
    user = request.user

    # Return default preferences plus user's stored theme from Django User model
    prefs = {
        "theme": getattr(user, "theme_preference", "system"),
        "accent": "teal",
        "density": "comfortable",
        "font_size": "medium",
    }

    if request.method == "GET":
        return Response(prefs)

    # PATCH
    data = request.data
    theme = data.get("theme", prefs["theme"])
    if theme in ("light", "dark", "system"):
        if hasattr(user, "theme_preference"):
            user.theme_preference = theme
            user.save(update_fields=["theme_preference"])

    prefs.update({
        "theme": theme,
        "accent": data.get("accent", prefs["accent"]),
        "density": data.get("density", prefs["density"]),
        "font_size": data.get("font_size", prefs["font_size"]),
    })
    return Response(prefs)


# ---------------------------------------------------------------------------
# User Settings (for the frontend SettingsUsers page)
# ---------------------------------------------------------------------------
@api_view(["GET"])
@permission_classes([IsAuthenticated])
def user_settings_list(request):
    """GET /api/settings/users/ → list all users (admin-only view)."""
    if request.user.role != "ADMIN":
        return Response({"detail": "Admin access required."}, status=403)

    users = UserModel.objects.values(
        "id", "username", "email", "first_name", "last_name",
        "role", "is_active", "date_joined", "last_login",
    ).order_by("-date_joined")
    return Response(list(users))


@api_view(["PATCH"])
@permission_classes([IsAuthenticated])
def user_settings_detail(request, pk):
    """PATCH /api/settings/users/{id}/ → update user (activate/deactivate, change role)."""
    if request.user.role != "ADMIN":
        return Response({"detail": "Admin access required."}, status=403)

    try:
        user = UserModel.objects.get(pk=pk)
    except UserModel.DoesNotExist:
        return Response({"detail": "User not found."}, status=404)

    data = request.data
    if "is_active" in data:
        user.is_active = bool(data["is_active"])
    if "role" in data:
        new_role = data["role"].upper()
        valid_roles = [c[0] for c in UserModel._meta.get_field("role").choices]
        if new_role in valid_roles:
            user.role = new_role
        else:
            return Response({"detail": f"Invalid role: {data['role']}"}, status=400)

    update_fields = []
    if "is_active" in data:
        update_fields.append("is_active")
    if "role" in data:
        update_fields.append("role")
    user.save(update_fields=update_fields)
    return Response({"detail": "User updated."})
