# Generated by Django 6.0.6 on 2026-07-07 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('crm', '0001_initial'),
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('invoice', 'Supplier Invoice'), ('receipt', 'Customer Receipt'), ('prescription', 'Prescription'), ('delivery_note', 'Delivery Note'), ('return_form', 'Return/Refund Form'), ('purchase_order', 'Purchase Order'), ('generic', 'Generic Document')], max_length=20, unique=True)),
                ('prompt_template', models.TextField()),
                ('extraction_schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('demand_forecast', 'Demand Forecasting'), ('supplier_scoring', 'Supplier Scoring'), ('expiry_risk', 'Expiry Risk Prediction'), ('reorder_point', 'Dynamic Reorder Point'), ('adherence', 'Patient Adherence Prediction'), ('anomaly', 'Anomaly Detection'), ('pricing', 'Pricing Optimization')], max_length=32)),
                ('version', models.CharField(max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('last_trained_at', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['model_type', 'is_active'], name='intelligenc_model_t_a2f459_idx')],
                'unique_together': {('model_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(max_length=32)),
                ('subject_id', models.CharField(max_length=36)),
                ('prediction', models.JSONField()),
                ('confidence', models.FloatField(default=0.0)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='intelligence.modelversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(max_length=32)),
                ('subject_id', models.CharField(max_length=36)),
                ('outcome', models.JSONField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='intelligence.predictionlog')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.FloatField(default=0.0)),
                ('cost_score', models.FloatField(default=0.0)),
                ('reliability_score', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(default=0.0)),
                ('speed_score', models.FloatField(default=0.0)),
                ('trend', models.CharField(default='stable', max_length=8)),
                ('analysis_json', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='catalog.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('unusual_order', 'Unusual Order Quantity'), ('unusual_dispense', 'Unusual Dispense Pattern'), ('stock_discrepancy', 'Stock Level Discrepancy'), ('price_spike', 'Supplier Price Spike'), ('unusual_velocity', 'Unusual Consumption Velocity')], max_length=24)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=8)),
                ('subject_type', models.CharField(max_length=32)),
                ('subject_id', models.CharField(max_length=36)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data_snapshot', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['anomaly_type', 'resolved'], name='intelligenc_anomaly_093235_idx'), models.Index(fields=['severity'], name='intelligenc_severit_a461e1_idx'), models.Index(fields=['created_at'], name='intelligenc_created_c20c2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpiryRiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='low', max_length=12)),
                ('estimated_exhaustion_date', models.DateField(null=True)),
                ('days_of_stock_remaining', models.IntegerField(null=True)),
                ('daily_consumption_rate', models.FloatField(default=0.0)),
                ('assessed_at', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='lots.lot')),
            ],
            options={
                'indexes': [models.Index(fields=['lot', 'assessed_at'], name='intelligenc_lot_id_806bdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField()),
                ('predicted_quantity', models.IntegerField()),
                ('confidence_low', models.IntegerField()),
                ('confidence_high', models.IntegerField()),
                ('method', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='catalog.product')),
                ('model_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_forecasts', to='intelligence.modelversion')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'forecast_date'], name='intelligenc_product_04cd27_idx'), models.Index(fields=['forecast_date'], name='intelligenc_forecas_ae7cc6_idx')],
                'unique_together': {('product', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='PatientAdherenceScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adherence_score', models.FloatField(default=0.0)),
                ('days_overdue_risk', models.IntegerField(default=0)),
                ('pattern', models.CharField(default='regular', max_length=16)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_scores', to='crm.contact')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['contact', 'product'], name='intelligenc_contact_ee549a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['model_version', 'created_at'], name='intelligenc_model_v_fd0d35_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['subject_type', 'subject_id'], name='intelligenc_subject_f15989_idx'),
        ),
        migrations.AddIndex(
            model_name='outcomelog',
            index=models.Index(fields=['subject_type', 'subject_id'], name='intelligenc_subject_3aa004_idx'),
        ),
        migrations.AddIndex(
            model_name='outcomelog',
            index=models.Index(fields=['recorded_at'], name='intelligenc_recorde_2ff6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierscore',
            index=models.Index(fields=['supplier', 'calculated_at'], name='intelligenc_supplie_2c0045_idx'),
        ),
    ]
