# Generated by Django 6.0.6 on 2026-07-07 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lead_time', models.PositiveIntegerField(default=3)),
                ('min_order_value', models.FloatField(default=0.0)),
                ('rating', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='catalog_sup_name_018e39_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('api', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=64)),
                ('soh', models.IntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(default=100)),
                ('max_stock', models.PositiveIntegerField(default=1000)),
                ('unit_cost', models.FloatField(default=0.0)),
                ('pack_size', models.PositiveIntegerField(default=1)),
                ('reorder_point', models.PositiveIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.supplier')),
            ],
            options={
                'indexes': [models.Index(fields=['api'], name='catalog_pro_api_d09a58_idx'), models.Index(fields=['name'], name='catalog_pro_name_f603c0_idx')],
            },
        ),
    ]
