# Generated by Django 6.0.6 on 2026-07-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('name', models.CharField(choices=[('gemini', 'Google Gemini'), ('claude', 'Anthropic Claude'), ('openai', 'OpenAI ChatGPT'), ('deepseek', 'DeepSeek'), ('openrouter', 'OpenRouter')], max_length=16, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('model', models.CharField(max_length=128)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('encrypted_api_key', models.BinaryField(blank=True, null=True)),
                ('fallback_priority', models.PositiveIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enabled', 'fallback_priority'], name='llm_llmprov_enabled_55ebd9_idx')],
            },
        ),
    ]
