# Generated by Django 6.0.6 on 2026-07-07 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('EXPIRY_WARNING', 'Expiry warning'), ('STOCKOUT', 'Stockout'), ('REORDER', 'Reorder'), ('REFILL_DUE', 'Refill due'), ('TASK_DUE', 'Task due'), ('APPROVAL_PENDING', 'Approval pending'), ('DEAL_UPDATE', 'Deal update')], max_length=20)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=8)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email')], default='IN_APP', max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read'], name='notificatio_recipie_6e3964_idx'), models.Index(fields=['notif_type'], name='notificatio_notif_t_5dbf49_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
